### ISSUE TITLE
Release for darwin_arm 

### ISSUE THREAD

**Issue by philipp1992** [alxrem/terraform-provider-hdns#1]
Hi,

thank you for this awesome terraform provider. 
Is there a chance you can build a release for the darmin_arm platform?

kind regards
Philipp

**Comment by alxrem** [comment]
Hello.
Do you mean darwin_arm64?

**Comment by philipp1992** [comment]
yes sorry for the typo.
Its darwin_arm64 for macbook m1

**Comment by philipp1992** [comment]
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/alxrem/hdns v0.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may
│ have different platforms supported.

**Comment by alxrem** [comment]
Try release v0.2.1

**Comment by philipp1992** [comment]
works. highly appreciated thank you
